// Central Dispatch API field definitions
export const CD_FIELDS = [
  { key: 'vehicle_vin', label: 'VIN', type: 'text', required: true, description: 'Vehicle Identification Number' },
  { key: 'vehicle_year', label: 'Year', type: 'number', required: true, description: 'Vehicle year' },
  { key: 'vehicle_make', label: 'Make', type: 'text', required: true, description: 'Vehicle manufacturer' },
  { key: 'vehicle_model', label: 'Model', type: 'text', required: true, description: 'Vehicle model' },
  { key: 'vehicle_color', label: 'Color', type: 'text', required: false, description: 'Vehicle color' },
  { key: 'vehicle_type', label: 'Vehicle Type', type: 'select', required: true, description: 'sedan, suv, truck, van, motorcycle, other', options: ['sedan', 'suv', 'truck', 'van', 'motorcycle', 'other'] },
  { key: 'vehicle_condition', label: 'Condition', type: 'select', required: true, description: 'operable, inoperable', options: ['operable', 'inoperable'] },
  { key: 'pickup_name', label: 'Pickup Location Name', type: 'text', required: false, description: 'Name of pickup location (e.g., Copart Dallas)' },
  { key: 'pickup_address', label: 'Pickup Street Address', type: 'text', required: true, description: 'Street address for pickup' },
  { key: 'pickup_city', label: 'Pickup City', type: 'text', required: true, description: 'City for pickup' },
  { key: 'pickup_state', label: 'Pickup State', type: 'text', required: true, description: 'State abbreviation (e.g., TX)' },
  { key: 'pickup_zip', label: 'Pickup ZIP', type: 'text', required: true, description: '5-digit ZIP code' },
  { key: 'pickup_phone', label: 'Pickup Phone', type: 'text', required: false, description: 'Contact phone for pickup location' },
  { key: 'pickup_contact', label: 'Pickup Contact', type: 'text', required: false, description: 'Contact person name' },
  { key: 'delivery_name', label: 'Delivery Location Name', type: 'text', required: false, description: 'Name of delivery location' },
  { key: 'delivery_address', label: 'Delivery Street Address', type: 'text', required: true, description: 'Street address for delivery' },
  { key: 'delivery_city', label: 'Delivery City', type: 'text', required: true, description: 'City for delivery' },
  { key: 'delivery_state', label: 'Delivery State', type: 'text', required: true, description: 'State abbreviation' },
  { key: 'delivery_zip', label: 'Delivery ZIP', type: 'text', required: true, description: '5-digit ZIP code' },
  { key: 'delivery_phone', label: 'Delivery Phone', type: 'text', required: false, description: 'Contact phone for delivery' },
  { key: 'delivery_contact', label: 'Delivery Contact', type: 'text', required: false, description: 'Contact person name' },
  { key: 'buyer_id', label: 'Buyer ID', type: 'text', required: false, description: 'Buyer/Member ID from auction' },
  { key: 'buyer_name', label: 'Buyer Name', type: 'text', required: false, description: 'Buyer name' },
  // F2 fix: Unified lot/stock number field
  { key: 'vehicle_lot', label: 'Lot/Stock Number', type: 'text', required: false, description: 'Auction lot or stock number (unified)' },
  { key: 'sale_date', label: 'Sale Date', type: 'date', required: false, description: 'Date of sale' },
  { key: 'total_amount', label: 'Total Amount', type: 'number', required: false, description: 'Total sale amount' },
  { key: 'notes', label: 'Notes', type: 'textarea', required: false, description: 'Additional notes or special instructions' },
  { key: 'transport_special_instructions', label: 'Transport Special Instructions', type: 'textarea', required: false, description: 'Special instructions for transport (appointment times, hours, etc.)' },
]
